### ISSUE TITLE
Can not to make Maileg run

### ISSUE THREAD

**Issue by danimela** [Mazzzieg/Maileg#4]
Hello guys, thanks for your work and your attention.
I was very interested in testing your Maileg program so I download everything, create credentials.json, put the email and keywords in config.py and tryed to run maileg but nothing happens... I can not see a main fonction.

This is the log created:
2024-01-22 12:07:54 - INFO - START OF A SCRIPT
2024-01-22 12:07:54 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-01-22 12:07:54 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-01-22 12:07:54 - INFO - Found 4 result(s).
2024-01-22 12:07:55 - ERROR - An unexpected error occurred: '<' not supported between instances of 'ApiInteraction' and 'int'

I must admit I am a beginner programmer so i am probably missing something. 
Any help would be welcome
Daniel

**Comment by danimela** [comment]
2024-01-22 12:07:54 - INFO - START OF A SCRIPT
2024-01-22 12:07:54 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-01-22 12:07:54 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-01-22 12:07:54 - INFO - Found 4 result(s).
2024-01-22 12:07:55 - ERROR - An unexpected error occurred: '<' not supported between instances of 'ApiInteraction' and 'int'

**Comment by Mazzzieg** [comment]
Hello Daniel! 
Thank you for testing our script! 
On the master branch, Maileg defines a main function without actually calling it, allowing users to personalize it as they wish. 
If you prefer not to create a separate file to import Maileg from Maileg.py, instantiate a Maileg class, and then call the main function, you can instead use the Maileg script from the archparse branch. In this branch, the main function is automatically called from the Maileg.py file (just remember to update your config file afterwards). 
I hope it helps but if you got any trouble or questions don't hesitate to reach out! :)

**Comment by danimela** [comment]
Hello Mazzzieg, the script works well for me with the arg parse branche. I found a couple of minors syntax problem in ApiInteraction.py file but once solved it seems to work. Here is the new log:

2024-01-22 17:05:48 - INFO - Starting email processing for the past 1 days.
2024-01-22 17:06:14 - INFO - "GET /?state=M4Qd...
2024-01-22 17:06:14 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-01-22 17:06:14 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-01-22 17:06:14 - INFO - Received 1 message(s).
2024-01-22 17:06:15 - INFO - Todays messages have been marked as read
2024-01-22 17:06:15 - INFO - Email processing completed.

Unfortunatetly the script is quite complex for me and I a can not manage it by myself to make it reply an unread message with the selected keyword. I do not want to ask too much but Would you have any more documentation ??
My last objectif is to connect it with an openAI Assistant to reply to certain emails and your script looks really powerful.

Thanks a lot for your help.

**Comment by Mazzzieg** [comment]
Great to hear that you've successfully run the script on the archparse branch and fixed the minor syntax issues in the ApiInteraction.py file!

Regarding the script not responding to emails with the selected keyword, it's possible that there might be an issue with the configuration in your config file. Could you please share your config file with us (ensuring any sensitive information is removed)? This way, we can help you troubleshoot the issue more effectively.

Thanks for your interest in our script, and I look forward to helping you achieve your objective!

**Comment by RowonMandM** [comment]
Hello Mazzzieg, it is really kind of you. I downcopy the script of the config.py file.
Thanks a lot.
Daniel

"""
#Configuration settings for the Maileg script. Set the variables to suit your specific needs.

# Gmail settings
USER_EMAIL: str = "admin@fonvirtual.com"

# Keywords that might be used by customer in mail, that script will be filtering and searching for
KEYWORDS: list = ["DevoluciónIA", "TEST"]

# NOT case-sensitive
CALENDAR_OPTIONAL_HOUR_NAME: str = "wolne"

# Choice of a language used in generating week day ('polski','german','spanish' or leave empty for english)
LANGUAGE = 'spanish'

# Email settings
def auto_reply(customer_name: str, workouts: str):
    """
    Function generating answer to a first mail.
    """
    # Message for auto-reply emails
    reply = f"""
Dear {customer_name},

Thank you for reaching out to us. This is an automated response confirming that we have received your email.
We will get back to you as soon as possible.

{workouts}

Best Regards,
[Your Name]
"""
    return reply

def workout_hour_form(date: str, day_of_a_week: str, hour: str, location: str):
    """
    Function generating single workout hour proposition.
    """
    hour = f"{date} ({day_of_a_week}) at {hour} in {location}"
    return hour

def auto_confirmation(date: str, day_of_a_week: str, hour: str, workout_in_correct_language : str, location: str, customer_name: str):
    """
    Function generating confirmation of scheduling a workout.
    """
    # Confirmations mail subject
    subject = f"Confirmation - {workout_in_correct_language.capitalize()} {date} ({day_of_a_week}) at {hour}"
    
    # Message for confirmation emails
    reply = f"""
Dear {customer_name},

This is a confirmation of scheduling your workout at {date} ({day_of_a_week}) at {hour} in {location}.
Can't wait to see you there!

Best Regards,
[Your Name]
"""
    return subject, reply
"""

**Comment by Mazzzieg** [comment]
Hello Daniel,

Thank you for sharing your config.py file. After reviewing it and conducting some tests, we've identified a minor issue that could be the cause of the problem you're experiencing. We have made the necessary updates to address this issue.

Please pull the latest update from the argparse branch of our repository. This update should resolve the problem and ensure the script functions as intended.

If you encounter any further difficulties or have additional questions, please feel free to reach out. We're here to assist you and ensure that your experience with our script is smooth and successful.

**Comment by danimela** [comment]
Hi Mazzzieg, thanks a lot for your help.

I have included all the changes your made and I encounter another problem. When running the maileg.py script, I'm encountering the error ValueError: min() arg is an empty sequence. I asked ChatGPT and It seems to occurs because the function min(self.dates) is being called within the calendar_stuff function in ApiInteraction.py, and self.dates is an empty sequence. The issue likely stems from self.dates not being properly populated, possibly due to no events being found in the queried date range or a logic error in filling the self.dates list.

I down copy the Visual Studio Code error message argparse/maileg.py"
"""
Recieved 2 message(s).
Received 2 new message(s) filtered as QUESTION(S).
Traceback (most recent call last):
  File "/Users/danielmela/Maileg-1.1 argparse/maileg.py", line 232, in <module>
    maileg_instance.main(argps.days)
  File "/Users/danielmela/Maileg-1.1 argparse/maileg.py", line 207, in main
    self.answering_to_mails(self.args.without_answering)
  File "/Users/danielmela/Maileg-1.1 argparse/maileg.py", line 182, in answering_to_mails
    self.api_interactor.answering_to_first_mails(without_answering_mode)
  File "/Users/danielmela/Maileg-1.1 argparse/ApiInteraction.py", line 689, in answering_to_first_mails
    self.calendar_stuff()
  File "/Users/danielmela/Maileg-1.1 argparse/ApiInteraction.py", line 92, in wrapper
    raise last_exception
  File "/Users/danielmela/Maileg-1.1 argparse/ApiInteraction.py", line 65, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danielmela/Maileg-1.1 argparse/ApiInteraction.py", line 447, in calendar_stuff
    f"There {be} ONLY {len(self.list_of_optional_hours)} optional workout hour(s) found in day(s) {min(self.dates)} - {max(self.dates)}."
                                                                                                   ^^^^^^^^^^^^^^^
ValueError: min() arg is an empty sequence"""

If you can not help anymore I understand.
Thanks again
Daniel

**Comment by kuba-sinski** [comment]
u can copy this:

```
if self.dates:
    print(
        f"There {be} ONLY {len(self.list_of_optional_hours)} optional workout hour(s) found in day(s) {min(self.dates)} - {max(self.dates)}."
    )
    self.logger.warning(
        f"There {be} ONLY %s optional workout hour(s) found in day(s) %s - %s.",
        len(self.list_of_optional_hours),
        min(self.dates),
        max(self.dates),
    )
else:
    print("No optional workout hours found.")
    self.logger.warning("No optional workout hours found.")
```

and paste instead:
https://github.com/Mazzzieg/Maileg/blob/eda034b3d1d92ec29242d74cb381f3fad228383a/ApiInteraction.py#L445-L453

to handle the error when no dates are available :)
This is the easiest way to handle this problem.

anyway, I made a fix for this problem, so if the change is merged, it will work fine 👍
